# For local debugging only
services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
    volumes:
      - chroma-data:/chroma/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chroma-data: