# For local debugging only
services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
      - IS_PERSISTENT=true
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    volumes:
      - ./data/chromadb:/data
    networks:
      - app-network

  chromadb-visualizer:
    build:
      dockerfile: Dockerfile.chromadb-visualizer
    ports:
      - "3000:3000"
    depends_on:
      - chromadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chromadb: