FROM node:18-alpine

WORKDIR /app

COPY visualizations/chromadb_visualizer/package.json  ./
RUN npm install

COPY public/ ./public/
COPY visualizations/chromadb_visualizer ./src/

EXPOSE 3000

CMD ["npm", "start"]